spring:
  application:
    name: book-service
  config:
    import: 'optional:configserver:http://localhost:8888'
    
app:
  book:
    image:
      bucket: bookstore-book-images-dev
      base-url: 'https://bookstore-book-images-dev.s3.us-east-1.amazonaws.com'
      folder: books
